# Nome do Workflow
name: Análise de Entropia CI

# Gatilhos (Triggers): Executa em push para a main ou em pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Definição dos Jobs
jobs:
  # Job único chamado 'build'
  build:
    # Sistema Operacional onde o job será executado
    runs-on: ubuntu-latest

    # Passos (Steps) a serem executados
    steps:
      # 1. Faz o checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala as dependências do projeto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Executa os testes unitários
      - name: Run unit tests
        run: python -m unittest test_entropy.py

      # 5. Executa o script principal de análise para gerar o gráfico e o relatório
      - name: Run entropy analysis script
        run: python analise_entropia.py

      # 6. Faz o upload dos artefatos gerados (gráfico e relatório)
      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: entropy-analysis-results
          path: |
            grafico_entropia_comparativo.png
            entropy_report.txt

